name: Check URLs
on:
  pull_request: {branches: ['main']}
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check URLs in docs
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          jobSummary: true
          args: --exclude "https://github.com.*.git|lycheeverse.*" **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
