name: Check URLs

on:
  pull_request:
  push:

jobs:
  links:
    name: Validate Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check URLs in docs
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          jobSummary: true
          format: markdown
          output: links-results.md
          args: >-
            --exclude-private
            --exclude "https://github.com.*.git|lycheeverse.*"
            --verbose
            --no-progress
            **/*.md
            **/*.Rmd
            **/*.Rd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
