name: Lint Code Base
on:
  pull_request: {branches: ['main']}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with: {fetch-depth: 0}
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_R: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
