name: pkgdown
on:
  pull_request: {branches: ['main']}
  push: {branches: ['main']}
jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    env: {GITHUB_PAT: "${{ secrets.GITHUB_TOKEN }}"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with: {clean: false, folder: docs}
