name: pkgdown
on:
  pull_request: {branches: ['main']}
  push: {branches: ['main']}
jobs:
  Generate:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build site
        run: pkgdown::build_site_github_pages(install = TRUE, dest_dir = "public")
        shell: Rscript {0}
      - name: Deploy to GitHub pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
