on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - 'presentation/**'

name: Publish Presentation

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install the quarto R package
        run: install.packages("quarto")
        shell: Rscript {0}

      - name: Render Quarto Project
        run: quarto render
        shell: bash
        working-directory: presentation

      - name: Publish Presentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./presentation/_site
          destination_dir: presentation
          force_orphan: true
