name: Publish Presentation Slides

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - 'presentation/**'
      - 'workshop/**'

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        QUARTO_DIR:
          - presentation
          - workshop
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash
        working-directory: ${{ matrix.QUARTO_DIR }}

      - name: Publish Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.QUARTO_DIR }}/_site
          destination_dir: ${{ matrix.QUARTO_DIR }}
