name: Publish Presentation

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - 'presentation/**'

env:
  QUARTO_DIR: presentation

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash
        working-directory: ${{ env.QUARTO_DIR }}

      - name: Publish Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.QUARTO_DIR }}/_site
          destination_dir: ${{ env.QUARTO_DIR }}
