on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - 'presentation/**'

name: Publish Presentation

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: presentation
          GITHUB_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
          GITHUB_USERNAME: 'github-actions[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
