on:
  push:
  pull_request:

name: R CMD check

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R deps
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build package
        runs: R CMD build .

      - name: Check package
        runs: R CMD check *.tar.gz
