name: R CMD check
on:
  pull_request: {branches: ['main']}
jobs:
  check:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: devtools::install_dev_deps()
        shell: Rscript {0}
      - name: Build package
        run: R CMD build .
      - name: Check package
        run: R CMD check *.tar.gz
