name: Spellcheck

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Spellcheck
    container:
      image: rocker/tidyverse:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Spelling Check test
        uses: insightsengineering/r-spellcheck-action@v2
